pixel-editor/pixel-editor.js

Adds the title attribute to the pixel art buttons, so it's easy to see what the buttons do by hovering over them﻿

add titles to pixel art buttons

---

dispatch.js
index.html
utils/validate.js

This includes improved error messages by stripping down the browser-given error message to only two things:
1. the stack trace (inside of the editor, not dispatch.js or any other gamelab files)
2. the type of error or message given by the browser.
This also adds the esprima library to check for errors ahead of time because the browser does not give you a stack trace for syntax errors. (Only runtime errors.)
This has been tested on the latest version of Chrome, and works fine. Fixes are needed for Firefox and Safari.
See #14 
Firefox: 
Safari:

Improved error messages

---

components/githubLink.js
components/nameBar.js
getPresignedURL.js
github.js

This PR changes references to hackclub/game-lab to hackclub/gamelab in the repo.
While there are no material changes to the AWS Lambda function, we should still deploy this to make sure the repo version and deployed version stay in sync. When merging, please update the code on Lambda as needed.

Change GitHub URL hackclub/game-lab -> hackclub/gamelab

---

Engine.js

i think this fixes the issue where the `collides` function is called before the objects actually collide
also fixes hitbox...
before: 
after:

fix collision issue

---

view.js

this gives the `show-options` div a semitransparent background color, so the text inside can be seen more easily.\
(also, a bit of padding, to make it look a tiny bit better in the wake of the background color.)

update .show-options styles

---

dispatch.js

Users are prompted to name their projects before saving if they haven't yet...
https://user-images.githubusercontent.com/5891442/159982874-708b8da0-c4e9-4702-a33e-8d554a93bbaa.mov
Only triggers if a name hasn't been set & doesn't trigger on automatic saves (ie. bug report generation)

Prompt rename on save for projects without names

---

components/menuButtons.js
styles/editor.css

Even though Gamelab isn't designed to support mobile, this PR makes the buttons list scrollable, allowing mobile users to run games.
Previously, if you were on a small device, the run button would be *just* out of reach.
Old buttons:
New buttons:
You can scroll the new buttons to access all of them.

Make buttons scrollable on mobile

---

checkerboard.svg
pixel-editor/pixel-editor.js

Tiny change that adds a checkerboard SVG to the "transparent" color option in the pixel editor (so it's more clear what that button does).

Add checkerboard pattern to transparent color option

---

yarn.lock

Affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS) in the ``isOriginPotentiallyTrustworthy()`` function in ``referrer.js``, when processing a URL string with alternating letters and periods, such as ``'http://' + 'a.a.'.repeat(i) + 'a'.``

CVE-2022-2596 Fixed [node-fetch Inefficient Regular Expression Complexity]

---

games/metadata.json

Empty string tags caused a weird visual glitch, removed those tags

Remove empty tags from metadata.json

---

games/metadata.json

Fixes duplicate entry for [`reactor.js`](https://github.com/hackclub/sprig/blob/main/games/reactor.js) by @sampoder.
Changes filename to `reactor` so it does not 404.

Fix metadata.json for reactor.js

---

games/shoot_green_blobs.js

This fix is for the game: `Shoot green blobs`
On repeatedly pressing "J" key for shooting even after dying throws the following error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'playback') on line 439 in column 9. 
Open the browser console for more information.
```
Fixed it in the commit below 👍

Fixed: Repeatedly pressing shoot key after dying throws error

---

upload.js

Add an explicit error on pushing to a device if the browser does not support the Web Serial API

Add error about Web Serial API

---

games/Breakout.js
games/desi-pong.js
games/pong.js

Pong, Breakout, and Desi-Pong all used `getState` to get the map dimensions. This is a browser implementation detail and doesn't exist on the Sprig, causing these games to break.
I updated the games to use the `width` and `height` functions instead. I'll be adding these to the docs as well as a note to avoid `getState`.

Remove getState from games

---

index.css

Firefox 91 is the current ESR on debian 11
It is also the last (recentish) version of a browser to not support image-rendering: pixelated;
So for now, it is changed to image-rendering: crisp-edges; on firefox browsers
> Example: Pushing boxes to the goal. (from [Sokoban Plus](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban_plus.js))
making existing games work on Firefox 91 (The ESR on debian 11)
> Example  : Press WASD to move, J to restart and K to toggle trails, Get A boxes (cyan) to A goals (green), Get B boxes (magenta) to B goals (red), Get normal boxes (gray) to either goal. (from [Sokoban plus](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub …

Add Support for Firefox 91

---

global.d.ts

This PR adds a `global.d.ts` file that can be used when developing a Sprig game using TypeScript.
I've covered all of the methods available in the documentation, but perhaps there are some I'm not aware of.
Even though keys, bitmaps, maps, colors and tunes are still strings, I'm using branded types to differenciate them

Add strong typings

---

docs/ASSEMBLY.md

While I was assembling my sprig console, I was a little bit confused on which screw length to use in step 2.
So I specified which length to use in both contexts (steps 2 and 6)

Add specifications for screw length in steps

---

games/pong-multiplayer.js

It is a version of pong that allows for 2 player multiplayer
| Player  | Up  | Down  | Colour |
|---|---|---|---|
|  1 |  W | S  | Black |
|  2 |  I |  K | Red |
- [ x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/). …

Add pong-multiplayer game

---

games/hot-digitty-dog.js

The game hot-diggity-dog had a bug where when the score reaches 100 or more, the number would show partially on the other side of the screen. This fixes that.

Fix the score overflow bug for real this time in the game hot-diggity-dog

---

package.json
yarn.lock

I used git bisect to determine that commit 2665941 was causing the problem with syntax highlighting. It put the yarn.lock into the repository, which is good practice for applications. I deleted the yarn.lock file and rebuilt it on the main branch. Syntax highlighting worked. It did update four packages.
There was also a warning about a dependency for lezer/common not being met, which I fixed by adding it to package.json.
After fixing the warning, I tried running the original lock file, but the bug was still present. So hopefully the rebuilt lock file fixes things. We'll see when it's deployed.

fix: Fix the syntax highlighting problem.

---

sequencer/sequencer.js

Fixing [this issue](https://github.com/hackclub/sprig/issues/617) by not letting the user input 0 (or lower), and the minimum BPM you can go is 1 (even though that is quite slow, that is the lowest you can go by setting the BPM through the slider).
<br><br>
Since there is a bug about the Map, Sprite and Tune editors not showing up, deleting the top comment about being an author brought them back, for some reason.

Constrain BPM input in the Sequencer.

---

sequencer/sequencer.js

Fixed [this issue](https://github.com/hackclub/sprig/issues/711) by updating the next note *after* playing the selected one, instead of it being the other way around.

Sequencer now plays selected note

---

docs/ASSEMBLY.md

Make it clear that you have to screw in the other D pad cutout as well before connecting the Rasberry Pi Pico.

Update spirg assembly docs

---

src/components/big-interactive-pages/migrate.tsx
src/components/popups-etc/draft-warning.module.css
src/components/popups-etc/draft-warning.tsx
src/components/popups-etc/migrate-toast.tsx
src/lib/game-saving/legacy-migration.ts
src/pages/~/index.astro

Fixes #885. The migration page now redirects through the helper when localStorage access is denied. I also added a warning on the opening modal.

Fix migration in Firefox and Safari

---

src/components/navbar-editor.tsx

Feels right because "Get a Sprig" is capitalised... though Sprig is a brand name

Capitalise "Games" / "Game"

---

src/components/codemirror.tsx
src/lib/codemirror/init.ts

Do not initialize the text in the editor using an undoable transaction

---

bin/lint-sprig
games/metadata.json

Re-adding games and lint-sprig script.

feature: Add lint-sprig script and missing games.

---

src/components/big-interactive-pages/editor.tsx

Firefox has weird tab restoring logic. When you, for example, Ctrl-Shift-T, it opens a kinda broken cached version of the page. And for some reason this reverts the CM state. Seems like manipulating Preact state is unpredictable, but sessionStorage is saved, so we use a random token to detect if the page is being restored and force a reload.
Fixes #919.

Do a full reload when tab is restored

---

src/pages/deprecated-file-player.astro

This adds a new route, `/deprecated-file-player`, which is a barebones player-only page that autoruns. It supports two URL parameters, `file` to load a file from URL, and `watch` to rerun when the file changes.
@khrj I recognize that this is more barebones than the original PR, but I wonder if this is enough to fix your workflow? If not, please let me know what you need.
Calling it deprecated because I don't want to encourage using this for anything except to un-break existing projects relying on the parameters you added in #644. I'm planning on likely removing this page if we publish an NPM package and make sure everything relying on this migrates over.
When merged this will fix #908.

Add file player to fix khrj's workflow

---

docs/UPLOAD.md

This PR adds a note to the uploading guide about using a supported browser and the `dialout` group if on Linux.

Add note about browser and Linux to UPLOAD.md

---

docs/SPRIG_APP_REVIEW.md

The goal here is to publish explicit directions on how we perform sprig app reviews, such that we can scale the sprig app reviewer team.

Add sprig app reviewer documentation

---

.github/scripts/plagiarism_check.py

After looking at recent workflow logs, I see that most of them with space or any special character have crashed the workflow so this change makes it so they are inside Quote so it runs normally.
example log where:
https://github.com/hackclub/sprig/actions/runs/7248565182

Quote The File Paths To Handle Special Characters

---

src/lib/game-saving/gallery.ts
src/pages/gallery/[filename].astro
src/pages/gallery/index.astro

This change will allow submitted apps to include their own change to the metadata.json which will be reviewed alongside all other things w/ the app.  Thus, the app will actually show up in the gallery such that we can ensure, for instance, the image displays properly.  This also will result in good, public review of the tags and metadata that go along w/ the apps.

Use the local version of the metadata.json instead of sourcing from github

---

docs/docs.md
package.json
src/components/big-interactive-pages/editor.tsx
src/lib/transform-detect-infinite-loop.ts
yarn.lock

the sprig editor will throw an error if
1. there are more than 2000 iterations in a loop AND
2. the loop takes > 1.5s to complete
addresses #1091 
add environment variables to Vercel deployment

add infinite loop detection

---

src/components/big-interactive-pages/editor.tsx
src/lib/state.ts

addreses #1414 
store the current value of isDark in localStorage
load the value of isDark from localstorage when the editor is rendering

make dark mode sticky acorss relaods

---

src/components/design-system/bitmap-preview.tsx

addresses #1437 
add a period in when calling bitmapTextToImage to avoid it breaking when rendering bitmap preview

fix map editor

---

src/components/big-interactive-pages/editor.tsx
src/lib/engine/index.ts

due to the location of the infinite loop detection code, some babel parse errors would not be bubbled up into the editor
this addresses #1426

move infinite loop detection to after parsing

---

src/components/big-interactive-pages/editor.tsx
src/components/design-system/textarea.module.css
src/components/design-system/textarea.tsx
src/components/navbar-editor.tsx
src/components/navbar.module.css
src/global.css
src/lib/state.ts
src/pages/api/stuck-request.ts

addresses #1433 
This adds a new UI element in the editor where Sprig users can report when they're stuck
Once they click "Send", their reports will be stored in an airtable base
...and sent through the `#playing-contact-points` slack channel where Slacker would be able to pick it up as an action item
A message looks like this 
Examples:

add "I'm stuck" tool to sprig editor

---

package.json
src/lib/engine/index.ts
yarn.lock

The `esprima` package has a bug where the spread operator does not work properly on objects (as described in [this issue](https://github.com/jquery/esprima/issues/2034)). There is a fork called [`esprima-next`](https://github.com/node-projects/esprima-next) where this issue is fixed.

upgrade esprima to esprima-next and fixing spread operator not working

---

package.json
src/components/navbar-editor.tsx

This pull request introduces an Auto-Format feature to the editor, aimed at improving code readability and consistency. The motivation behind this feature is to provide an easy-to-access tool for users, especially beginners and those participating in hackathons, to automatically format their code. This addresses the common issue of inconsistent code styling, such as indentation and spacing, making the codebase cleaner and easier to read.
Added **stripWhitespaceAndUpdate** function to include js-beautify options.
Added a menu item "Prettify code" in the dropdown, linked to the updated function.
**Before: Code that's a bit all over the place.**
**After: Nicely formatted code that's easy on the eyes.**

Introduce Auto-Format to Sprig Editor  #1399

---

src/components/popups-etc/help.module.css

This isn't a game! (I'm still making mine!)
It's a small fix for a visual thing I recently dealt with in HCB. `overflow: scroll` also adds a horizontal scrollbar, so I've changed it to `overflow-y: scroll`.
Before:
After:

Remove extra scrollbar in help pane

---

src/pages/api/gallery.ts

Adds an API route (`/api/gallery`) that supports gallery game fetching.
Supported Query Params:
+ `new`: Filters only new games
+ `query`: Returns all games that match query
+ `tags`: A comma seperated string of tags that games must include

Gallery API Route

---

src/pages/index.astro

Fixed the links to the hardware and firmware. Before they led to a depreciated repo now they lead to this maintained repo.

Link fix on home page

---

src/components/navbar-main.tsx
src/components/popups-etc/announcement-banner.module.css
src/components/popups-etc/announcement-banner.tsx

Adds an announcement banner to the website for the current ongoing game jam

feat: create announcement banner for penny game jam

---

firmware/spade/src/rpi/CMakeLists.txt

the raspberry pi pico sdk, by default, compiles the build date into the output binary. this PR disables that functionality.

spade: make builds deterministic; don't compile in build date

---

firmware/spade/docker/dockerfile
scripts/gardenshed/gdb-client.sh
scripts/gardenshed/gdb-server.sh

this gives gdb access to the full source tree for debugging, allowing you to view code as it's being run in GDB

run gdb client in docker instead of host

---

src/components/big-interactive-pages/editor.tsx

Modify logic to catch exception when casting the theme string to a ThemeType and default to 'light' theme

---

src/components/popups-etc/chat-component.tsx

previously the chat session id would change each time the page was re-rendered causing requests to be blocked due to rate-limiting

set the chat session id once when the chat is opened

---

src/components/popups-etc/chat-component.tsx
src/lib/codemirror/util.ts

previously the client chat feature will send 2 requests to the llm api. the first being a copy of the current code and then the chat message sent by the user.
with these changes, we hash the code and only send a new copy of the code to the server when the hash of the current code in the editor is different from the previous one.

send a new copy of the code to the server only when the code changes

---

src/components/popups-etc/chat-component.tsx

Previously after closing the sprig editor window llm chat sessions were not properly ended. 
With these changes, a request will be sent to the server to end that chat session once the window is about to be unloaded

properly end session after the page is onloaded or the page is closed

---

src/lib/game-saving/email.ts

I've setup a separate SendGrid api key for preview deployments as another security measure to protect the main api key used.

use email set in environment variables

---

.gitignore
src/integrations/generate-metadata.ts
src/integrations/thumbnail.ts
src/lib/thumbnail.ts
src/pages/gallery/gallery.tsx
vercel.json

#1396 
Right now, every time you perform a search the game thumbnail is re-fetched from the server. 
Now game image data is generated at build time and stored in the public folder. These image data are cached through vercel resulting in less resources transferred.

store a copy of gallery images to avoid re-fetching

---

.github/scripts/generate-metadata.js

the metadata integration does no longer require the `img` tag

update workflow script

---

astro.config.mjs

because the thumbnail api function was removed and the game preview json files was only generated at build time, astro will optimize and remove the games since they were only read at build time as compared to every time a request was made when using the thumbnail api function

keep game files in production build

---

src/integrations/thumbnail.ts
src/middleware.ts

Because we want tot differentiate between db, http, and signaling server (in the future) metrics

Add http prefix to web requests

---

src/lib/engine/error.ts
src/lib/engine/index.ts

I shifted the line numbers so they align with the actual errors and added line numbers to infinite recursion and URI errors.

fixing line numbers in sprig editor error handling

---

.github/workflows/typescript_check.yml
.github/workflows/unit_tests.yml

I put the synchronize type in the wrong file - I'm moving it to the right one here.

Fixing github action - Moving synchronize to the right file

---

games/Sprig Dash.js
games/sprig_dash.js

**Author:** Akshat Khurana
My game is about constantly jumping over incoming obstacles, both on the ground and in the air.
Its super simple, press J to jump and thats all you need to do.

Sprig Dash

---

src/components/big-interactive-pages/login.tsx
src/pages/api/auth/submit-code.ts

Previously, the Sprig editor will fail to correctly set the lockoutUntil in firebase because the lockout duration was not taken as a valid number.

cast environment variables to valid numbers for comparison/usage

---

src/components/popups-etc/draft-warning.tsx

the "start coding" button should be disabled based on whether the email is valid- this was broken by #2125 and fixed in this PR

fix wrong disabled conditions for login page

---

src/components/codemirror-widgets/open-button.tsx
src/components/popups-etc/editor-modal.tsx
src/components/subeditors/sequencer.tsx

Fixes #2312 
The two useEffect's in `editor-modal.tsx` can be naughty but they help ensure two things
1. If an update comes from the underlying codemirror document, the first effect doesn't run as we're already updating the editor modal from there
2. If an update was originally made from the currently open editor modal, the changes to the codemirror document will not trigger an update to the open editor modal 
Both of these help us avoid Out-of-order errors or Cycles

fix tune editor going of sync and throwing `Out-of-order effect` error

---

src/middleware.ts

https://plausible.io/docs/events-api

add plausible server side analytics

---

src/components/popups-etc/room-password.tsx

Most elegant solution I could find. fixes #2418

Check empty password on password-prompt page load so that rooms without password can be immediately accessed

---

src/components/codemirror.tsx

Fix bug where room participants wouldn't update

---

src/components/big-interactive-pages/editor.tsx
src/components/popups-etc/editor-modal.tsx
src/lib/codemirror/init.ts

resolves #2368 
when a change is propagated to bitmaps/map/tune, their template literals get unfolded and the change applied. however, they're not closed back. this change forces the template literals to fold after these changes have been applied to the editor.

fold template literals after update has been propagated in editor

---

games/Cash-Clicker!.js

Author: 3XAY
The goal is to make as much money as possible!
This game is a port from a Scratch game I made a while back. I really enjoyed it and thought it would be perfect to play on the sprig  while you wait for something.
I also had a lot of fun learning how to take something from block coding and convert it into JavaScript, a language I had never used before. (I've only used Python and Java before this).
- W to click the coin (this gives money!)
- I to open/close the shop (ya gotta spend money to make money!)
- J to purchase "AC" or autoclicker, this gives you x amount of money every second. (x is written to the left of the button, price is written below)
- L to purchase "CPC" or clicks per click, this gives you more money …

[Sprig App] Cash Clicker!

---

src/components/navbar.module.css

On the Recent deploy , both UI for Github PR button and dropdown of Github had stop showing due the recent commit made on #2561 where the use of `white-space: nowrap; /* P3baf */` caused the issue. This PR removes that and fixes the issue
Why did it broke?
The main case of using this `white-space: nowrap; /* P3baf */` is to remain the container or items on a single line without wrapping. Our UI with multiple text , input field exceeds the container width and it got clipped causing the UI to not show up causing it to break it.

Fix UI Not Displaying For Run On Device & Github PR

---

games/StickRunner.js

The game had an extra bracket that gave an error so it was unplayable. This pr removes that bracket.

Fixing StickRunner Game

---

games/TheTombOfAThousandTerrors.js

The game had the error "SyntaxError: unknown file: Cannot redeclare built-in function: getGrid (570:0)". I renamed the function, so it works now.

Fix The Tomb of a Thousand (T)errors Game

---

games/The_impossible_game_l1.js

The comment at the end of the game was never closed making it unplayable.

Fix The_impossible_game_l1.js

---

games/mailman.js

A function was defined twice which made it unplayable.

Fixing Mailman.js

---

games/Atari-Breakout.js
games/bout.js

Author: HildingL
This is a replica of the classic Atri Breakout. The goal is simple, bounce the ball and try to remove all of the pink boxes. You hav won when all the pink boxes are gone. Morover the speed of the ball increases the longer into the game you are. The hardest part to code of this game was the bouncing macanism of the ball and its ability to remove boxes.
Use a and d to move the platform. Bounce the ball between the platform, walls and boxes, to remove all of the pink boxes. You die if the ball touches the bottom of the gameboard. The goal is to remove all the pink boxes.

[Sprig App] Atari Breakout
