hackclub/sprig

- dispatch.js
- view.js
Fixes the error message by displaying the raw stack instead of the JSON
> Fix newlines in error message

- components/bugReport.js
- dispatch.js
- editor.css
- save.js
- Adds the `REPORT_BUG` dispatch event
- Links the `REPORT_BUG` dispatch event to the bug button
- Adds the option to not copy the URL upon saving (disabled by default, only used for the `REPORT_BUG` dispatch event)
- Makes the images in buttons display pixelated instead of blurry
> Add bug reporting

- LICENSE
- README.md
This PR does a quick pass on the README to try and explain Game Lab and its goals a little more.
I would encourage merging this, and then doing a pass yourself @leomcelroy to better articulate what we're all about with Game Lab!
> Do a pass on the README

- Engine.js
- pixel-editor/pixel-editor.js
- ced tweak
- remove cam abstraction so leo no eat me
> Support dragging in smaller images + support vector scale for mirroring

- dispatch.js
Re-implements #40 with the new iframe-sandboxing system.
> Re-add concise error messages

- index.html
The account is already setup for this [here](https://plausible.io/gamelab.hackclub.com), so this change should start working as soon as the PR is merged.
> Switch plausible.io reporting 'hackclub.com' -> 'gamelab.hackclub.com'

- dispatch.js
> Update challenge docs for challenges 1-4

- README.md
> Update readme according to #74

- README.md
closes #73.
i split the sentence in half, hopefully that's okay?
> add command to last step of running instructions

- Engine.js
- components/renderDocs.js
- Document obj.scale
- Implement, document obj.props
> Throw error when unknown prop passed to e.add, add e.props

- init.js
> Update default cartridge to engine 0.2.3

- engine/baseEngine.js
Fix getTile using `state.dimensions.height` insted of `state.dimensions.width` for x verification
> fix(getTile): wrong variable use

- ASSEMBLY.md
Closes #233 
Could use some revisions, but I think it'll do for now.
> Initial pass on assembly instructions

- docs/docs.md
> Implement copy suggestions in #245

- dispatch.js
> Add navigator.clipboard to automatically copy share link

- games/minesweeper.js
The typical Minesweeper game, but built with Sprig!
[Editor Share Link](https://editor.sprig.hackclub.com/?id=eb1b81ad1863b43c3eeb698cd0d8c1f7)
> Minesweeper

- games/minesweeper.js
Cleaned up code, added comments.
Fixed game ending without all flags placed.
> Updated minesweeper.js

- view.js
> Revert "Serve logo locally"

- docs/docs.md
Runs after ever input event has finished being handled. Useful for tasks like checking win states:
Add Y after ever
> Fix a typo in the help menu.

- games/tictactoe.js
I created tic tac toe for sprig!
> Add tic tac toe

- games/shoot_green_blobs.js
> shoot green blobs

- confusing_conditions.js
- games/confusing_conditions.js
This is a confusing game. It’s meant to be a twist on your expectations. Use WASD keys to move and J to reset the level you’re currently on.
I had experience coding but not using JavaScript, so this was an interesting experience for me!
> Confusing Conditions

- Flurffy.js
my 3rd game for sprig.
A version of Flappy Bird
Complete all levels in 35 seconds to win
> Flurffy game

- games/color_patterns.js
- games/pong.js
- games/sokoban_plus.js
I couldn't find out how to fix 9 puzzle. Sorry.
> Fix most games.

- games/snake_game.js
Before Fruit was appearing on Snake Body due to which Head of the Snake get detached from its body. Now the problem is FIXED. In future if I encounter with any problem, I will surely fix it.
> Fruit Appearence Bug Fixed

- games/snake_game.js
If any problem is faced during playing this game, please let me know.
> RESET Functionality Added

- games/Falling Blocks.js
Dodge the falling blocks for as long as you can. Use A and D to move.
I have experience coding in Python, but I do not have as much experience with JavaScript.
> Falling Blocks

- games/flappy_bird_but_no_gravity_and_worse.js
I hope the name wasn't too long... ;)
> Create Flappy Bird with No Gravity

- games/color_domination.js
- games/metadata.json
This game was created at Sprig Jam! :)
> Add color_domination game

- games/reactor.js
_(my not so great game... but it is two player?)_
> ⚡ Add the Reactor game!

- games/alien_invaders.js
Simple clone of the classic space invaders game.
Use the A and D to move the player around.
Use the W or I to shoot.
Press J to replay.
> alien_invaders

- games/Candy Rush.js
Try to get the candies in the mouths.
-No pushing candies with other candies; there are ways to position your character to not have to do this to win -The black blocks are walls, which your character cannot pass through.
> Candy Rush!

- games/puzzle_runner.js
In my game, you have to navigate through a maze while pushing a box until you reach the goal point.
> puzzle_runner

- README.md
- games/getting_started.js
Updated tutorial wording to match the link one is directed to click.
I had no idea what `vite` was, so I looked it up and added a link to it in the readme.
Very cool project!
> Small update to documentation and tutorial

- games/Virtual_Machine.js
@cedric-h came to dream and asked for a fix so had to get out and full fill the reality ;)
> Fixed FontSize Error , Fixed Level being Null!

- games/Zooter.js
My dad showed me sprig, and I was wanting to get a game done and up on your gallery. I had a lot of fun making this, and this is an awesome project!
> I added a file for a game I made for sprig.

- games/PushBattle.js
PushBattle:
This game is a two player pushing game. Players have to push each other into hazard blocks to win the round. The game can be played for an unlimited amount of rounds since it will keep track of rounds and wins for each player. My next step in this game's development is to create a random map each time the game resets. For my first game I ever created it was a good experience overall. Once I learn all the capabilities of this software I will be able to make great games.
> PushBattle

- games/push_ the_blocks.js
Added a new game called Push The Blocks.   This was really fun to make!
> Push the Blocks

- games/virus_plowing.js
I have already submitted this game, just want to update it
> fix bug where it would kill the player twice

- games/cave_explorer.js
Cave Explorer is a game about mapping out the caves that you've encountered along your way. My experience coding is a 6/10.
> Cave Explorer

- games/coding_demo_5_gravity.js
- games/metadata.json
> showing off gravity
> W to jump, AD to move left and right
> woo gravity

- games/the_invisible_man.js
The goal is to collect coins, but your character is invisible.
You control your character with the W A S D keys
Additional comments: 
The game outputs some very basic debug info into the browser console. That was the only debug stuff I did not delete, in case
someone wants to know where the invisible man exactly is, so that they can confirm, that there is actually an entity there, and I am not just wasting their time. Or if for some reason you wanted to cheat in the game.
Also I should mention that I am a beginner at JavaScript, and this is my first serious work
If you need to contact me, my E-mail address is: gblevel2017@gmail.com
- [✔] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [✔] The game is placed …
> the_invisible_man

- games/delightful_mazes.js
made by @hephaestushex
> My game is basically several mazes, but you have no indications of walls or exits (they're invisible). To win, you must also push the secret trapdoor open. Your score is based on how much you open. Open them all and you win!
> Use WASD to move and J to go back to start of the level
Don't have specified thumbnail
> Added my game Delightful Mazes

- games/Electrikoban.js
> Pushing wires to power the lights.
> Example  : Press WASD to move, J to reset the level and I to display help.
> Add Electrikoban

- games/chuckman_go.js
Avoid enemies throughout the path and reach the goal!
Press WASD to move, J to restart, Get to the finishing position (yellow) by avoiding all the enemies.
> New Game - Chuckman Go!

- games/Meteor_shower.js
> The goal in the game is to get the rocket to the coin, without touching any meteors.
> Press WASD to move, and K start the game. If you finished the game, press "run" to start again.
> Meteor shower

- games/loadsamoney.js
> This is a small tycoon-like game about making cold, hard green, with various upgrades you can use along the way to streamline your process. Go from button mashing to securing your descendant's futures, just a few clicks and presses away!
> [WASD] is used to run your money press. As you reach various stages in the game, you can buy upgrades using [IJKL], such as money printers(automate button presses) and money men(multipliers). Additionally, you can get the ultimate flex, the 24k sprig! Impractical, sure, but who cares, anyway?
---
> Prices are as followed;
> Money printers: 200$
> Money men: 500$
> Money banks: 1250$
> 24k Sprig: 5000$
`Not applicable; I didn't make one. Please let me know if I need …
> LOADSAMONEY

- games/Bottom_of_the_Barrel.js
You fight enemies in a typical RPG style combat system, with the aim of climbing to the top of the barrel.
A and D for moving in game, WASD for navigating menus, J for select, W when player is infront of a ladder or chest.
- [ /] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- [/ ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [/ ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [/ ] The game runs without errors. 
- [/ ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ /] …
> Bottom of the Barrel

- games/Fish_in_the_Sea.js
> The objective in each level is to get to any portal. 
> WASD to move, J to reset the level. Each move costs one energy (even if you hit a wall!). Collect an energy boost to increase your energy. Have fun!
> Fish_in_the_Sea

- games/Icy Portals.js
> You play as a snowman going through magic portals to reach the next level. You only have 20 moves per level, so use them wisely.
> Use WASD to move the snowman around. The game has ice physics, so the snowman will continue moving forward until it hits a wall. The finish point can only be interacted with if the snowman stops on it. On some levels, there are blue and purple teleporters that will teleport the snowman to each other. Just like the goal, they will only work if the snowman stops on them. On 2 levels, there are red buttons that will delete the block to the right of them. Just like before, the button will only work if the snowman stops on it. Press J to restart the level.
> Icy Portals

- games/Flurffy.js
Just a small update for Flurffy.
@LucasHT22
> Bugfix and improve text

- games/Worldcraft.js
You control a little blob. There is no objective to this game, just explore the world and build things. You get different items by picking up different things. 
WASD to move, L to pick up things to your right, J to set things down to your left. Use I to change which item to drop, you will see a star appear next to the name of the item.
> Worldcraft

- games/lights_out.js
> The objective of the game is to flip all tiles so that all of the lights on the 5x5 grid are off. An additional goal is to do so with the fewest number of moves.
> WASD moves the cursor around. 
Pressing K will flip the tile underneath your cursor and the four tile adjecent to it (above, below, left, right).
If you get lost or confused, just press I and the level, timer, and move counter will be reset.
This is based on the original ["Lights Out" game by Tiger Electronics](https://en.wikipedia.org/wiki/Lights_Out_(game)).
I created 20 different levels increasing in difficulty. All of them are tested and solvable.
I also have tried to document the code as much as possible, so that anyone going through the code may learn something from it. …
> Add Lights Out game

- dispatches/init.js
- `run=true` can be set to run the code given in file immediately 
- `hide=true` can be set to not show the editor, just the run window
- `watch=X` can be set to refresh the file param every X milliseconds
Each of these params require `file=` to be set
Example:
```
https://editor.sprig.hackclub.com/?file=http://localhost:3000/build.js&run=true&hide=true&watch=1000
```
This will reload the file from http://localhost:3000/build.js every second (if it has changed), while also immediately rerunning it, and not displaying the editor
> Add run, hide and watch url params

- games/13 medium sokoban puzzles.js
> Pushing boxes into the goals and completing all 13 levels
> Press WASD to move, J to restart, Get the brown/red boxes to the black dots. Boxes cannot push other boxes and you cannot move through black squares.
Did not use an image
> 13 medium sokoban puzzles

- dispatches/init.js
only auto run file when trusted and warn user if not trusted
> fix security bug (#496)

- games/black_jack.js
Updated formatting within the js file and fixed a exploit where you could claim a win multiple times.
> Update black_jack formatting and little exploit

- UNTITLED (1).js
- get_the_birdie.js
> Example: Pushing boxes to the goal. (from [Sokoban Plus](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban_plus.js))
> Example  : Press WASD to move, J to restart and K to toggle trails, Get A boxes (cyan) to A goals (green), Get B boxes (magenta) to B goals (red), Get normal boxes (gray) to either goal. (from [Sokoban plus](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban_plus.js))
> Get_the_birdie

- games/sprigadventure.js
> Dodging fireballs while navigating a maze.
> WASD for moving, I for pause menu, get to the green box at the end of the level, and pass all the levels until you get to the win screen with a smiley face.
> SprigAdventure

- games/Cross_The_Road.js
> Example: Pushing boxes to the goal. (from [Sokoban Plus](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban_plus.js))
> Example  : Press WASD to move, J to restart and K to toggle trails, Get A boxes (cyan) to A goals (green), Get B boxes (magenta) to B goals (red), Get normal boxes (gray) to either goal. (from [Sokoban plus](https://editor.sprig.hackclub.com/?file=https://raw.githubusercontent.com/hackclub/sprig/main/games/sokoban_plus.js))
- ✔ The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/).
- ✔ The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- ✔ The code is …
> Added restart in Cross_the_Road.js

- docs/GROWING_A_SPRIG.md
When I was reading through the file GROWING_A_SPRIG.md, I noticed a few ambiguous/unclear sentences in the last "WIP" section. The commit I proposed should improve the quality of that file and make it sound more professional.
> Fix some grammar mistakes in GROWING_A_SPRIG.md

- games/Amongus flight.js
This game is about maneuvering your among-us character in through the blockers set by the imposter. As the game progresses it gets harder, I took inspiration from subway surfer.
Press the buttons "a" and "d" to move left or right to avoid hitting the blockers set by the imposter.
- [ x] The game was made using the [Sprig editor](https://editor.sprig.hackclub.com/). …
> Amongus Flight

- games/cube_escape.js
My game is about a cube that was wrongfully sentenced by trying to escape cube prison.
Press `WASD` to move.
Press `L` to shoot a bullet to the right.
Press `J` to shoot a bullet to the left.
Shooting brown box and enemies, removes them.
Navigate to the `gray` warp portal to change to the **next** level.
Navigate to the `red` warp portal to change tp the **previous** level.
Navigate to the `green` warp portal to **restart** the current level.
If you touch the enemy ( green cube officer ) on any side you will lose 1 hp.
If your hp reaches 0 you restart.
You can touch the key item to unlock locked walls, after losing 1 hp you will **lose** the key.
No Image
> Cube Escape

- games/hot-digitty-dog.js
This was my game in pr #718. I realized that I had a bug later. I hope this is the right way to make a pr for this.
> Fix the locked in a box bug for the hot-diggity-dog game

- games/explorer.js
Navigating through an abandoned laboratory to kill enemies.
"w" is up, "s" is down, "a" is left, "d" is right".
Move to the sword, and press "i" to grab it. You can only do this once.
Without the sword, you're immune to monsters and can push stumps,
but that on its own won't get you far.
With the sword, you're able to kill monsters and walk through walls,
but you're able to be killed.
Swap between having a sword and not having a sword by hitting "i". While
having the sword in your hand, you also hit anything within a one-block
radius.
Beat all enemies in the red room to win the game.
INTENDED ORDER
The intended order is to do: yellow => green => purple => orange => red,
but I've given it a more non-linear layout for player freedom purposes. …
> Added new Sprig game

- games/bullet_dodge.js
- Fixed bullets not spawing on bottom row
- Fixed bullets not causing damage on edges
- Fixed and consolidated some variable naming errors
- Limited number of onscreen sprites
- Reduced calls to setHealth() function
- Improved bullet movement section of script
> Various bugfixes and optimizations to bullet_dodge.js

- games/cube_escape.js
Updated `cube_escape.js` and added a `How to play` section, a changelog and most importantly slow motionCan be enabled / disabled by setting the `slowMotion` variable to the corresponding value. i.e. Set it to true if you want slow motion or to false to disable slow motion. Slow Motion works by looping *after* a player movement.
> feat: Added Slow Motion for cube_escape.js

- games/squarey_runs_away_from_the_fireball.js
This game is a two-player game where the fire needs to catch "Squarey" (a character in my cousin's cinematic universe). WASD controls Squarey and IJKL controls the fire.
After 30 seconds, press any key to restart. You win if you survive 30 seconds.
> Add `squarey_runs_away_from_the_fireball`

- games/Tic Tac Toe.js
> It's a basic TicTacToe implementation built upon [Atharv Gupta](https://raw.githubusercontent.com/hackclub/sprig/571d13b475a0a547c70535a9e2b46788d742f847/games/Tic-Tac-Toe.js)'s original version. My remake aims to fix some bugs and provide a more clean GUI, better code structure, without pixel offsets, etc..
> Use `WASD` to move your cursor and `I` to set your cross or circle. You win if you either score 3 of the same symbols in a horizontal, vertical or (anti)-diagonal direction.
> 🎮 TicTacToe - Remake of Atharv's version

- games/Find_The_Suspect.js
* Fixed bug that still allowed selecting defendants even though the game was already over
> Fixed a minor bug (`Find the Suspect`)

- games/Falling_Water.js
Added walls, a cursor, and the ability to delete elements!
> Falling Water 2.0 Update

- games/rescue_leo.js
It's about a sea turtle which needs to go through mazes of trash to reach the goal tile, but if you die you restart from level 1!
It was quite fun to code, even though I'm not used to JS.
Press WASD to navigate through the mazes of trash, but don't touch the walls(trash).
> Rescue Leo- Sprig

- games/sprig_shoot.js
Shooting angry guys that are approaching you and not shooting bombs.
WS to move. J to shoot. When prompted, K to restart.
> Sprig Shoot

- docs/ASSEMBLY.md
2. Add spacers and put the longer screws through the holes and screw the bolts on on the other side.
> i added the something

- src/pages/~/index.astro
> Include unnamed games in game count

- games/Labyrinth3.js
The final installment of the simple labyrinth game where you would find the exit.
Simply, you would use W to move up, A to move left, S to down, D to right and J to restart.
> Labyrinth3

- games/bobs_bad_apple.js
Bob is trapped in a maze. Eat apples to get through the maze.
I am a new coder and I want a Sprig please. Now I know a bit more. Also I am this guy's son. I'm using this account because I am not 13 yet to have my own Github account.
w, a, s, d controls to move.
There are pushable blocks.
An image is not used.
> Add bobs bad apple to games folder.

- games/Dodge The Rock.js
- games/Dodge_The_Rock.js
You have to dodge the rocks coming your way. If you manage to dodge you get points. There are different difficulties that make the game more fun to play. Once you get hit by a rock the game ends. 
You have to press "s" to go down and "w" to go up.
> Dodge The Rock

- games/Binary_Eater.js
It is a game where the player has to provide input as binaries through (WASD)
```
w = 0
a = 1
s = 10
d = 01
```
There are custom binary codes from `a-z` (provided in the js file), the player has to type characters using these commands as quickly as possible, then it gets eaten up by a binary-eater (he looks like: `(> ^_^)>`). The goal is to type the characters before the eater comes to eat, without typing wrong binary values, and trying to score much as possible.
> Add Binary Eater Game

- games/CatchIt.js
**Shrey Mehra**
**This is a simple game where we have to catch the falling points**
**We can play this game by using a and d keys**
> Added CatchIt

- games/fill_the_map.js
**Author:**
##About Fill the Map
**The game is about to fill the map without overlaping or going back
**How to play
> fill_the_map.js

- src/pages/gallery/index.astro
Implement #841, fix the wording on the gallery page as @alhardwarehyde suggested.
> Update Gallery wording

- games/Space Invaders.js
- games/space-invaders.js
Space Invaders
Written Carmel Barkaee
Originally developed by Tomohiro Nishikado
Defeat the alien invaders before they reach Earth
Controls:
A/D - Left/Right
I   -    Shoot
Contact me: carmelbarkaee032708@gmail.com
> Space Invaders

- src/pages/api/games/save.ts
For tracking daily active users. Uses its own table so that we can also keep track of anonymous users.
> Add tracking for daily edits by user

- src/pages/gallery/index.astro
Just fixed a tiny error in the gallery.
> Fixed a minor spelling error

- src/lib/engine/1-base/text.ts
> Throw console error if glyph doesn't exist.

- src/lib/engine/1-base/text.ts
PR #1030 does not allow the space character to be rendered, throwing an error instead. This PR allows space as a character to be rendered.
> Let space be rendered

- games/fungi-frog-maze.js
The game file was using an old sprite that causes issues when loading on the gallery 😅
> Fix broken sprite at fungi-frog-maze.js

- games/Orpheus'_Burger_Dash.js
**Author: Samson C**
To objective is to make as many cheeseburgers as possible without getting rotten eggs on your burger. Every time you make three burgers, the game speeds up 50ms.
Press W and D to move, I to start, J to restart.
> Added Orpheus' Burger Bash

- games/Sprig_Boy.js
**Author: Kai Devrim**
**Play as the lonely sprig boy trying to achieve a trophy to present to his parents but can't seem to reach it easily, maybe his ability to create boxes to the left and right of him! Solve many puzzles using a unique play style inspred by the Nintendo game, BoxBoy!**
**Press WASD to move, W is jump but there is gravity. Use J to create a box to your left and L to create a box to your right. The goal is to get to the trophy at the end of the level. The boxes can move and are affected by gravity.**
> Add Sprig Boy!

- README.md
Made the "Sprig is a" section more understandable and easy to follow.
(Not a game, simply an individual who wants to help make this amazing project just a little better.)
> Improved README.md readability

- games/getting_started.js
- games/getting_started.md
Improvements to getting started tutorial. **Requires #1081**.
- Moved comment chunks to tutorial panel.
- Added code comments into game.
- Clarified wording in instructions.
- Added useful links, hints, solutions, and where to get help in instructions.
A demo with the tutorial panel can be found [here](https://sprig-tutorial-sam.vercel.app/gallery/getting_started). Note that **authentication is bypassed** in that demo, enter a random email and 6 digit login code and do not put sensitive information.
Resolves #1077.
> Improve getting_started tutorial

- games/Battleship.js
**Author:** [Johna-123](https://github.com/Johna-123)
**What is your game about?** It's a battleship game where you try to find and desrtoy your opponents ships.
WASD to move cursor
I to rotate ships (when placing)
J to confirm position of ship/attack
> Add Battleship.js

- games/killer_training.js
**Author:** jakjakob
shooting a puppet while trying to find the right way (sometimes through a maze) in a certain time
WASD to move, IJKL to shoot. IJKL determines the directions you shoot, bullet has 2 range. You can't touch the puppet or you'll restart the game. By missing the shot you have to restart the level (and you lose 5s)
No Image used
> Added game killer_training

- games/killer_training.js
- games/metadata.json
references my issue https://github.com/hackclub/sprig/issues/1142
> fixed issue where my game wouldn't open on gallery

- games/killer_training.js
How to play etc.. https://github.com/hackclub/sprig/pull/1141
Tutorial is also in the game itself
Now in version 1.1.0
1.1.0
Practice mode (not time limit and no restart if enemy touched)
Complete menu redesign:
- main menu has a button interface, with various options
- main menu shows highscore
- tutorial rewritten
- pages are controlled by key input
- shows version number
Highscore counter 
New finish screen with highscore, score and option to go to main menu
Go on menu instead button on restarts
Failing tutorial brings you back to main menu
2 slight level updates (mazes)
> Updated game killer_training

- games/find_the_watermelon.js
**Author: Mohamad**
My game is about a character who is trying to get the watermelon across the maze. There are walls and bombs which are preventing him and the character has to work around it.
Press WASD to move, J to restart, Get the watermelon icon but having your character on it (you will go to another level).
no images 
> Find the Watermelon submission

- games/shooter.js
**Author:**
Tyler Sousa
Shoot zombies. Just a survival game, no ending other than dying
WASD to move, K to shoot, L to reload
> make shooter game

- src/components/spriki-components/Docs.astro
> Fixes mouse hover for sprikipedia main page buttons and slight design change

- src/pages/sprikipedia/index.astro
- src/translations/en_US.json
- src/translations/pt_BR.json
> no redundancy in the title of the sprikipedia main page

- README.md
> add slack channels to README

- src/lib/game-saving/account.ts
- src/pages/api/auth/submit-code.ts
- src/pages/api/games/delete.ts
- src/pages/api/games/rename.ts
- src/pages/api/games/save.ts
Add metrics for firebase CRUD operations
> instrument firebase operations

- A Space Odyssey.js
**Author:**
CondolentFire10 - Devon S.
An exciting spaceship flying simulator in which you must avoid crashing into asteroids or the boundary, and survive as long as possible!
Use J to start the game (or restart after death), and use wasd to move the spaceship around.
> Space Odyssey

- README.md
- RESPONSIBILITIES.md
Formalizes responsibility / accountability for the Sprig project
> Add responsibilities

- src/lib/engine/index.ts
addresses #490 
Will throw an error if a user redefines a library function
> throw error if user redefines library function

- src/pages/gallery/index.astro
> show 10 newest games first

- games/metadata.json
addresses #1105 
the date property on games was written as "added on" in [metadata.json](https://github.com/hackclub/sprig/blob/main/games/metadata.json) for the most recent games and so they would not be taken into consideration when sorting games.
> update metadata 'added on' -> 'addedOn'

- games/bomb_dodge.js
submission of game to sprig gallery
**Author:**
AstralTurtle 
Survive for as long as possible from the exploding bombs.
WASD to move. bomb can be pushed. It explodes in straight lines on x and y axis. …
> bomb dodge

- src/lib/game-saving/account.ts
> add timing to sprig db operations

- src/components/design-system/input.tsx
- src/pages/gallery/gallery.css
- src/pages/gallery/gallery.tsx
- src/pages/gallery/index.astro
add chronological/alphabetical sort order to sprig gallery
moved the gallery component to React for more reactivity
resolves #1289
> add sort by release date and sort by name in ascending/descending

- .github/workflows/check_plagiarism.yml
Gave Writing Permission to .github/workflows/check_plagiarism.yml so it can post the result.
> Added Write Comment Permission for Workflow.

- src/pages/gallery/gallery.tsx
- include author in search parameter
- filter showed items using block/none display
> improve search

- .github/workflows/workflow_run.yml
upgrading github-script version from 4 to 7 for workflow run
> Upgrading github-script version

- src/components/popups-etc/announcement-banner.module.css
this was bothering me
Before:
After:
> centralize banner

- src/pages/index.astro
Was just looking at the Sprig site and noticed a couple grammar issues in this paragraph on the home page.
> Fix wording of hardware development kit paragraph

- games/find_the_clone.js
**Author:**
TheGoldenBlock
My game is about differentiating very similar boxes to find the odd one out, and then pushing it to the goal. 
Use WASD to move, j to reset.
- [ x] The game name is not the same as the others …
> Find the Clone

- .github/scripts/extract_percentages.py
- .github/workflows/workflow_run.yml
Removes the No Plagiarism Found text and only posts if it detects
Check if the comment has already been sent so it doesn't repost when workflow runs again
> Remove No Game Found Text ||  Fixed multiple Plagiarism Report

- games/marble-tilt.js
**Author:** jdogcoder
Based on a suggestion from Zrl, Marble tilt is inspired of of the [marble tilt games](https://cloud-pfh6jdg27-hack-club-bot.vercel.app/0image__1_.png) where you try and get a marble into the whole
press WASD to control the board's "tilt", indicated by the red arrows on the sides. Your goal is to move the purple marble to the green square while avoiding the red/orange lava. Black squares are obstacles, and grey walls are borders. Once you hit the green square you will move to the next level. End screen should say win but I had no energy left to make a `w` so it just says `in` lol
> Add Jasper's Game ~ Marble Tilt

- package.json
- yarn.lock
the sprig engine recently had changes addressing #1194 & #1040 
with this package update, these issues should no longer be a problem
> update sprig package version

- src/components/subeditors/sequencer.tsx
After right-clicking on a sprig sub-editor the cell content should get deleted.
#1415
> right click to delete note in music editor

- src/components/navbar-editor.tsx
Added an easier way to log out from the editor page, without having to go to "my games"
> add log out button to editor nav dropdown (closes #827)

- src/pages/gallery/gallery.css
- src/pages/gallery/gallery.tsx
> Better Gallery Tagging UI & QoL fixes

- src/components/subeditors/sequencer.tsx
as mentioned on #905 , i have added clear button which clear the sequence rather than right click each line.
> Add Clear Button on Tune Editor

- package.json
- src/components/navbar-editor.tsx
Reverts hackclub/sprig#1475
Actually upon closer review this has some issues. It shouldn't remove all whitespacing between lines.
> Revert "Introduce Auto-Format to Sprig Editor  #1399"

- src/components/popups-etc/upload-failed-warning.tsx
- src/lib/upload.ts
- src/pages/editor.astro
as requested on #1356 now i have implemented a delay check and show warning if upload doesn't work properly
the ui for the warning currently is : 
Happy to change the codebase if there a different rules regarding ui changes etc.
> FIX - Show Warning On Upload Failed

- firmware/gardenshed/gardenshed.py
Default case seemed to be operating strangely, so I've removed it for now.
> remove default case from gardenshed

- src/components/navbar-editor.tsx
This should fix an issue where the Vercel deployment shows directory listing
> import entire js_beutify module before getting beutifier function

- scripts/gardenshed/README.md
> add alias info to readme 

- scripts/gardenshed/gardenshed.py
> disambiguate flashing

- firmware/spade/src/rpi/main.c
> PRESS ANY KEYS -> BUTTON

- src/lib/engine/index.ts
fixes the issue of #1557 where the map editor shits itself upon a bad `setLegend()` call due to bad handling of invalid data :)
> Fix for #1557

- src/lib/game-saving/email.ts
- src/pages/api/auth/email-login-code.ts
- src/pages/api/games/save.ts
This is an extension on top of #1575 to set the user's ID if they are already logged in
> Set the user ID in Loops if the user is already logged in

- src/lib/state.ts
> enable busker theme

- firmware/spade/README.md
> fix script location

- src/components/navbar-main.tsx
> feat: remove penny banner

- src/components/big-interactive-pages/mobile-player.module.css
- src/components/big-interactive-pages/mobile-player.tsx
- src/pages/gallery/[filename].astro
The mobile game gallery doesn't correctly determine the size of `vh` due to a flawed implementaion of `vh` (There is no clear guidance there when it comes to handling device and browser-specific differentiations)
[Demo Screenshot](https://cloud-p8xdgk8x2-hack-club-bot.vercel.app/0screenshot_20240228-132210.png)
> Mobile Player

- src/components/big-interactive-pages/editor.tsx
- src/components/big-interactive-pages/login.tsx
> prevent help area to resize above output area height

- games/Catch the Acorn.js
- games/Catch_the_Acorn.js
**Author:**
Anna I
A hungry squirrel trying to collect acorns to eat.
You press WASD to move and J to restart. Get player to touch the goal (acorn). Push the boxes and go through holes to get to the goal. Avoid the traps (green acorns).
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The name of the file/game contains only alphanumeric characters, …
> Catch the Acorn

- games/underground_escape.js
Ezra York
**Author:**
Ezra
You wake up trapped in a dungeon underground. Your main goal is to find the real key and unlock to lock to the exit. You might also come across fake doors or be fooled by the levels too.
use W, A, S, D to move. When you find the right key the lock will vanish.
There will also be movable walls so if you can't find a way in a area check the walls :)
> Underground Escape

- games/Davinci Lit Demo.js
- games/Davinci-Lit-Demo.js
**Author: RubixTV**
my game is inspired off of Mario Brothers and is a demo for the actual version I will make later (its to help kids have fun with studying for school). but gotta avoid acid/carrots and pass about 5 levels. 
A (left) D (right) W/I (jump). K (resart level) L (resart game). Get strawberry past carrots to get to bright yellow goal. Mystery boxes along the way to give jump bost. avoid acid, jump on carrots to explode them. 3 lives
> Davinci Lit Trivia demo

- FRC CHARGED UP.js
- FRC-CHARGED-UP.js
Wyatt Adolph
**Wyatt459:**
Use the robots to move the cones and cubes to your alliance grid trying to score as many as possible
in the fastest amount of time.
Each grid can hold 10 game pieces. Game pieces can not be used to
move other game pieces. The first one to fill their grid wins. Game pieces can be moved over the
charging station. To restart the game turn the console off and back on again. Game pieces can NOT be 
moved away from walls so be careful. Robots can make contact so you can play some defense.
Blue controls: W = up
S = down
A = left
D = right
Red controls: I = up
K = down
J = left
L = right        
> FRC CHARGED UP

- games/LaserGuide.js
**Author:**
extner.zip
You need to rotate the mirrors so the laser reaches the goal
use j and l to select a mirror
use k to rotate the selected mirror …
> LaserGuide

- Alien poop.js
- Alien-poop.js
**Author: Luis Guerrero**
Lalo
This game uses a alien from another world to push a poop inside of a toilet to clear the world from waste
In this game you will use W A S D to move the character all 4 directions. You will push the box into the goal to further move past levels.
> Alien Poop 

- src/components/popups-etc/help.tsx
> disable ai help if not logged in

- games/Exodus.js
**Kavin Jayakumar**
**Avoid the moving ogres and get to the end of the level.**
**Press WASD to move.**
> Added Exodus, my sprig game.

- games/Orb Journey.js
- games/orb_journey.js
**Author: Alex Nguyen**
My game is a short simple game involving two orbs: a water and a lava orb. The goal of this game is to get the orbs to their respective destinations through small little obstacle courses. The water orb can only go through water tiles, while the lava orb can only go through lava tiles. This game is speedrun-able, so players can play for a faster time each run.
The water orb moves using WASD keys and the fire orb moves using IJKL keys. You can reset the game using J once completed.
> Orb Journey Sprig Game

- src/components/big-interactive-pages/editor.tsx
- src/components/navbar-editor.tsx
> Add button to fold all bitmaps and export function from editor

- games/celeste.js
**Author:** DillonB07
**What is your game about?** Celeste: Sprig Edition is an adaptation of the 2018 [Celeste](https://celestegame.com) by Extremely OK Games. (I highly recommend playing that game, it is awesome!).
It's a beautiful & very difficult platformer game. My adaptation is extremely difficult but features strawberries, dashing & spikes - all mechanics in the original game.
This is a v1, I'd love to add more levels, improve the art & add more mechanics in the future!
Press A or D to move left/right, J to dash in combination with WASD. (Diagonals work too!) and I to jump.
> Add Celeste: Sprig Edition v1

- games/Party Games.js
- games/Party_Games.js
**Author:**
Iambodha
Play Party Games with your friends like SPY (only this gamemode currently available). Party games are meant to be played in person with the console being passed around.
Gamemode SPY : Everyone gets the same word except the SPY who does not know the word. You go in turns telling each other the words related to the word you got while the SPY tries to fit in and guess the word before the timer ends.
Party Games does not need any specific instructions as all information is included when playing the game. Ex. Selection Buttons and More.
> Party Games

- package.json
- yarn.lock
> update package version

- src/components/codemirror.tsx
> Revert "Fix editor bug caused by repeatedly replacing CodeMirror instance"

- src/components/codemirror.tsx
> Revert "Fix effect"

- src/lib/upload.ts
> fix ALL_GOOD not being read from serial buffer

- games/CatCatchSushi
changed name of game to be more accessible
**Author:**
> Update and rename DoNotConsumeEmptyBowls.js to CatCatchSushi

- .github/scripts/extract_percentages.py
- .github/workflows/check_plagiarism.yml
- .github/workflows/workflow_run.yml
This change fixes some of the bugs that seem to be failing background.
This also fixes the issue of the workflow failing and not sending text when plagiarism is detected.
> Fix Plagiarism Workflow

- src/legacy/homepage.scss
after two hours, it ended up only being one line of code lol
> Fixed problem on landing page with not all content fitting

- games/jumping_banana.js
**Author:** Ernests
Jumping to avoid hitting into blocks of dirt
Press W to jump, J to restart. You can double-jump and even triple-jump.
> Jumping banana

- games/Slap-A-Fish.js
**Author: Ben Park**
In this game your objective is to slap fish as fast as you can when they pop up on the screen.
The faster you act, the more points you are awarded.
Press 'l' to start. The diagram does a good job of explaining controls and button maps
> added my game: Slap-a-Fish

- games/Path_Master.js
> Revert "Revert "Path Master""

- package.json
- src/lib/engine/error.test.ts
- yarn.lock
I added 9 unit tests that check whether or not the normalizeGameError function is returning the right output - this is the error message that displays on the sprig editor. Right now, these will all fail since the function is returning incorrect output.
> Adding unit tests for error handling in the sprig editor

- .github/workflows/unit_tests.yml
- package.json
Adding the a github action to run the unit tests on pull requests.
> GitHub unittest action

- src/lib/engine/error.ts
Previously unit tests would fail
> Add line offset to prevent failures

- games/CrusaderTheGame.js
**Author:** Skyfall
A platformer where you have to go get
WASD to move, get keys and coins, then go to the portal. If you die, you have to restart from the beginning!
> Add Crusader

- games/sokobanlike.js
a short sokobon game with optional portals
**Neptune Ryan:**
**a short sokobon adventure using portals**
**use WASD to move, L and K to shoot portals for the final level**
- [x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)
NOT USED
> SokobanLike

- src/legacy/_shared.scss
- src/pages/index.astro
Added "play a game" button and simplified "make a game" button to always go to a new game.
> Modifying Landing Page Buttons

- src/components/big-interactive-pages/login.module.css
- src/components/big-interactive-pages/login.tsx
Removed the background and centered the login rectangle.
> Changed login page to have the same theme as the gallery

- src/components/big-interactive-pages/login.module.css
- src/components/big-interactive-pages/login.tsx
- src/components/popups-etc/project-name-creator.module.css
I combined the styles of both pages so they both look better and are more consistent.
> Merged styles of create game and login pages

- src/pages/~/new-game.astro
I added a navbar to the create game page.
> Added a navbar to the create game page

- src/components/big-interactive-pages/mobile-player.tsx
closes #2004 
i hope this doesn't break anything
> fix audio bug

- games/Divine_Tree_Man_Saves_A_Forest (3).js
- games/Divine_Tree_Man_Saves_A_Forest.js
**Author:**
Rohan
My game is about you, a divine tree man, who's goal is to save his forest form fires and fungus. If you can make it to the end, the Zire absorbs the evil force trying to destroy the forest, the Ezir. Everything is normal after Ezir is eradicated.
WASD to move, i to reset
Push the fungus into the fire
Push Zire onto suspicious spots(looks like wall but the character can walk over it) to delete parts of wall
Push suspicious walls with the Zire (looks like wall, but can be pushed by the Zire. Only one can be pushed at a time by the Zire)
The last level is super difficult, but if you know the mechanics it is easy. Dot fall for the 3 fake exits, only go through the colorful block to finish the game.
There are 7 …
> Divine_Tree_Man_Saves_A_Forest

- games/Stickman.js
**Author:**
Benjamin Faershtein
Simple stickman game
Collecting diamonds and having fun
WASD to move, J to reset
> Addded Stickman game

- games/the_great_robbery_ jailbreak!.js
**Author: Navya Singh**
**2 player maze where players are 2 robbers trying to escape prison and they have to use keys to open the gates and beat each other to the finish**
**Robber 1's controls are WASD to move. Robber 2's controls are IJKL to move.*
- [ x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ x ] The game name is not …
> the_great_robbery: jailbreak!

- games/maze.js
Emily Liu
My goal of my game is to have the prisoner break out of the jail by reaching the flag in a maze style. 
Press WASD to move and J to restart. In some levels, there will be also buttons you have to push by moving the prisoner to the same tile as the button. Also in some levels a warden is chasing you/trying to reach the flag before you so you will want to go as fast as you can so you don't get caught.
> Prison Break

- games/Maze_Escape_Reach_The_Yellow_Box.js
**Author nickname: Owski**
**In my game you start as a pumpkin character with three health who is trying to escape the maze. There are many enemies, such as the purple blocks (game code: moving obstacle), the angry cannon (gamecode: moving enemy), evil disc (game code: movingdisc), and the spikes (game code: obstacle). the purple block deal one damage and move up and down many tiles at the start of each map before settling down to moving up and down one tile a few seconds after, this provides a challenge because you must adjust your escape strategy based on the purple blocks changing movement pattern. the angry cannon is an interesting enemy and deal 1 damage every time it hits you. the angry cannon moves left one tile every time the pumpkin man (you) make an input. The spikes deal …
> Maze_Escape_Reach_The_Yellow_Box

- games/falldown.js
**Author: Alakh**
This is a recreation of the falldown game!
Use AD to move and J to start/reset!
> Added falldown mini game

- games/CONWAYs_GAME_OF_LIFE.js
**Author:**
Jules
Functional replica of [Conway's game of life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life)
W, A, S, D : Move the cursor
I, K            : Change the simulation speed +/-
J               : Reset game
L               : Switch tile state (dead/alive)
- [ x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x ] The game runs without errors. 
- [ x ] The name of the …
> Add game: Conway's Game of Life

- games/Dragon_Duel_v1.js
**Author:** giragon6
**What is your game about?** Simple two-player dodging game with gravity.
**How do you play your game?** Press W (P1) or I (P2) to flap and D (P1) or J (P2) to shoot a fireball. Hit your opponent with your fireballs and avoid the ones they shoot back!
- [ x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
- [ x ] The game is placed in the in the [`/games` directory](https://github.com/hackclub/sprig/tree/main/games).
- [ x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x ] The game runs without errors. 
- [ x ] The name of the file/game contains only alphanumeric characters, `-`s, or `_`s.
- [ …
> Dragon Duel

- games/Rock Paper Scissor (4).js
- games/Rock Paper Scissor.js
**Author: Yash Jain**
yash
its about rock paper and scissors
> Rock Paper Scissors

- games/Clicker Kingdom.js
**Author:** max
clicker kingdom is a management clicker game where your goal is to grow your population to 100!
WASD to move, hold L to gather resources, press I to upgraded infrastructure to gather resources faster, the higher your population the more resources you gather. press J to see stats and K to see info about the controls and objectives.
> clicker-kingdom

- games/PlasticPickup.js
**Author:**
pizzalover125
Collecting recyclable materials (plastic bottle) and not collecting unrecyclable materials (batteries).
Press a to move right, d to move left. Don't collect the batteries, but collect the plastic bottles to improve your score.
> added PlasticPickup to the games folder

- games/Galaga.js
Galaga-ish, a game by wormmeatapple!
**Author:**
wormmeatapple
A classic arcade game! Shoot aliens without losing your lives and try and reach a highscore!
W A S D to move your spaceship
I to fire bullets
K to start the game at the main menu
L to go to main menu once at the game over screen
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The name …
> Adding Galaga

- games/circuit-breaker.js
**Author:** Stefan D
You have to make your 'circuit' to the objective in a maximum number of moves, but there are also patrolling 'ghosts' trying to stop you!
Press WASD to move. Get your Circuit, to the Objective (marked), in a set number of moves, while trying to be stopped.
> Circuit Breaker

- src/components/big-interactive-pages/editor.tsx
- src/components/navbar-editor.tsx
- src/lib/state.ts
> fix stopping game from running

- games/color dino.js
**Author:**
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)
> added my game color dino

- src/components/popups-etc/draft-warning.tsx
- src/components/popups-etc/editor-modal.tsx
fixes "or continue without saving your work" button not working
https://github.com/user-attachments/assets/e23b9ed8-0263-4faa-a185-05d2f727faa8
> fix "continue without saving work" button

- src/components/popups-etc/out-of-space.tsx
> slots -> blocks

- games/Sewer_Flood.js
**Author:** Eduardo
Lasting as long as possible in a flooding sewer by jumping on top of water pipes.
Press WASD to move. Press J to catch a falling powerup while you are over it. Jump on top of falling pipes to avoid the water. The game begins 2.5 seconds in. The pipes pick up the pace during the game.
> Updating Sewer_Flood

- games/Cheese_Collector.js
**Sonya**
There are 5 levels. As the player progresses through the game, the level becomes harder and harder. The player plays as a mouse, aiming to push cheeses to their home.
Press WASD to move and J to restart.
> Cheese_Collector

- games/Evil astrokittens.js
you can check out the game here! https://sprig.hackclub.com/share/H3uSycQ1M8PRVTbcv5X4
Dragos Matzu
It is a simple space shooter where the enemy is a bunch of kittens each with they're own ability that make the game even more challenging 
The game is set in space where a kitten empire has conquered the galaxy and the player must bring them down with the final boss
w- shoot
a- go left
d- go right
s- start
- [x ] The code is significantly different from all other games in the [Sprig …
> Evil astrokittens

- games/JB_Dodge_game.js
Justin M Burns
Dodging meteors for as long as possible
move back and forth with A and D keys while dodging meteors
- [ x] The game name is not the same as the others from [gallery](https://sprig.hackclub.com/gallery)
> …
> added JB_Dodge_game.js

- games/classicpongX2.js
**AVSC**
Classic Ping Pong by Atari remixed with power ups ported to sprig
Press W to move ur paddle up, S to move paddle down and hit the ball …
> Atari classic pong X2 by AVSC

- src/components/popups-etc/project-name-creation.tsx
> fix new game form

- games/lasers_vs._fog.js
> Manual fix of tag

- games/Sound_Memory.js
> Update Sound_Memory.js added tags

- games/Crossy Road.js
> Update Crossy Road.js added tags

- games/Dont Touch the Cat.js
> Update Dont Touch the Cat.js added tags :)

- src/components/popups-etc/editor-modal.tsx
> Revert "fixes #2304"

- src/pages/gallery/[filename].astro
- src/pages/gallery/beta/[filename].astro
Previously, it was excepting and 500-ing.
> Make gallery 404 when no game exists

- src/components/navbar-editor.tsx
- src/components/navbar.module.css
> Fix run button aesthetic

- src/pages/sprikipedia/brand/index.astro
> Solve pcb.svg error on home page(fixes #1860)

- games/Put a _Sprig_ in your step.js
- games/Put a _Sprig_ in_your_step.js
Grhu (GunksterGrhu)
You play as a little sprout character and you have to  "put a Sprig (spring) in your step" and jump your way through the levels to collect leaves, watch out for thorns on your journey!
you use the WASD keys to jump your way around, and for easy controlling with jumping and moving sideways with a Sprig, you can use the "i" key to jump.
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [ x] The game …
> Put a Sprig in your step

- .github/workflows/post-vercel-comment.yml
Test PR made for workflow testing.
> Working On New Game Preview

- .github/workflows/post-vercel-comment.yml
Changing Running Action as currently pull_request has only read only permission as it's from forked repo
> Change Running Action

- .github/workflows/post-vercel-comment.yml
Making Small Changes to fix the current error
> Fix Workflow

- .github/workflows/post-vercel-comment.yml
This make the preview comment more readable
> Final Version Preview Link

- games/Monster-Mauler.js
Author: Dumbhog
Monster Mauler is a retro shooter game where you try and get as high as a score as possible before the time runs out or you die, The game features action packed gameplay and contains an additional challenge...
Shoot as many enemies as you can before the time runs out! and make sure to not get too close to them! Once you are done, you can take on the boss challenge if you wish.
Controls:
Moving: WASD
Shooting: IJKL
Activating Boss: Press "i" after beating the first challenge
> [Sprig App] Monster Mauler

- Car Park Escape.js
**LilySky22**
**Oh no! What bad parking, you've been trapped.  Solve the puzzle, move the cars, escape the car park**
**IJKL to move the selector then WASD to move the item selected. Simple!**
> Car Park Escape

- src/lib/codemirror/util.ts
> Fix bug where editor would freeze when block of code was deleted

- games/Snake-Bird-Knockoff.js
Author: CreativityShark
Snake Bird but recreated on Sprig. Control the Snake Bird to make it to the portal and move to the next level, avoid spikes, and eat apples to make the Snake Bird grow.
W - Move Up
A - Move Left
S - Move Down
D - Move Up
The Snake Bird is affected by gravity, and will fall downwards unless one or more segments of its body are supported by the ground.
> [Sprig App] Snake Bird Knockoff

- games/Snake-Bird-Knockoff.js
My apologizes for forgetting to update this before merging.
> Correct addedOn date for a game

- games/Save-The-Seas.js
Author: RyanBran888
The player is a fish, and has to swim to the ocean to collect the litter and save the world!
wasd to move the fish
> [Sprig App] Save The Seas

- games/Escape_From_Evil.js
**Author:** noobieyuh
**What is your game about?** 
My game is about escaping a monster cove to get back home. You go through portals to escape the monsters.
**How do you play your game?** 
You use WASD to move up, down, left, and right. You move on to the next level by going through a portal (purple). You must avoid the monsters (red). If you touch the monsters, you get sent back to the beginning. There are barriers/walls (x) that will make escaping harder.
> Escape From Evil

- games/Shooting-Stars!.js
Author: SpamixOfficial
This game is a worse remake of the 1980s retro game Space Invaders! It features dynamic map generation with obstacles, a dynamic amount of enemies! Except that, the lasers are also blocked by the obstacles to make the game a little harder :-)
The game is basically infinite, so finally you can play the game for over a year straight!
WASD to move, L for laser, J to restart
> [Sprig App] Shooting Stars!

- games/fox-runner.js
Author: fennecsdev
A maze game where you need to go to every tile of the maze while avoiding obstacles.
Use WASD to move the player around the maze, head to the flag once the level is filled
> [Sprig App] fox runner

- games/Find-Tommy.js
**Author:** Mysteryman386
My game is about finding Tommy, who is hiding from the omnipotent magnifing glass. Throughout the game, you would have to reveal boxes, unlock doors, and travel through hallways to try and find Tommy. There's also a time feature, move count and coins in order to increase replayability
WASD to move, J to select tommy/pick up loot, L to search suspicious boxes, K to restart. The aim is to find Tommy by searching through boxes and solving obstacles.
> Find Tommy

- src/middleware.ts
> Remove cache from editor, because it caused the game to not load correctly

- games/dot10.js
Author: ashfelloff
It's a basic ten-level maze game for me to explore JS and Sprig.
Use the arrow keys!
> [Sprig App] dot10

- games/WCfinal.js
Author: pulvis16
score as many goals as possible and have fun
must be two players commands wasd and jkil.
> [Sprig App] WCfinal

- games/Be_Younique.js
Author: pixelianWarrior
eliminating enemies to reach new levels each having their own mechanics
WASD to move, IJKL to shoot, shoot the enemies while dodging bullets, the ammo count in the corner relates to how many bullets you can shoot, if it runs out, you must get an ammo pack
> [Sprig App] Be_Younique

- games/Saving-Blob.js
Author: ARTISM30
Avoid the obstacles (walls/fake walls) and get the pink blob into the portal by pushing it.
WASD move up down left and right. J to reset level.
> [Sprig App] Saving Blob

- .github/workflows/unit_tests.yml
- package.json
- yarn.lock
Pass environment variables to cross-env using test-runner.
> use cross-env to pass environment variables to test runner 

- games/Cyan.js
Author: Boyceyboo
Try to make the whole screen cyan!
You have to use WASD and IJKL depending on the level
> [Sprig App] Cyan

- src/components/GalleryGame.tsx
- src/pages/gallery/gallery.tsx
fixes #1396 
fixes an issue where game image gets mixed up during search
> separate gallery game into its own component

- games/offline_t-rex_game.js
The game was broken cause the metadata was outside the comment.
> Fixing offline_t-rex_game.js

- src/legacy/homepage.scss
- src/pages/index.astro
Added at the request of @JaredSene -- let me know if it's too jarring or should be moved somewhere else
> Add a jam button

- games/maze runner 2.js
- games/maze_runner_5.js
**Author:**
Sagrusea
its a simple maze game with about 2 minutes of playtime
you need to collect keys to unlock doors, also dont touch the unhappy enemies, if you do you can gain hp by touching green + sprites, sometimes you also need to push a box to get somewhere
WASD for movement, J to reset level and L to unlock locks
> Maze runner 5

- games/Flappy-bird-with-animated-bird,-gravity-and-sound.js
Author: yug-khandelwal
Flappy bird with animated bird, gravity and sound. The bird animates by flapping its wings every second. The bird also falls down after every second to make this game a little difficult to play. The player needs to go through obstacles to earn points.
Use W to move up and S to move down
> [Sprig App] Flappy bird with animated bird, gravity and sound

- games/epic-space-invaders.js
Author: iLikeToCode
Lasers fire from the player, kill 25 for faster lasers, kill 50 for win
Move around as lasers spawn from the player to kill enemies
A and D to move left and right
> [Sprig App] epic space invaders

- games/Trinfin.js
Author: PaoloSp8
you are a gnome that's trapped in a cave, you must get out by any means possible!
Welcome to the world of Trinfin, a gnome who you will help get out of this chaotic world full of boxes, and not just. To free Trinfin, you'll have to pass through several levels, among which you will clear some easier ones and more challenging ones, and you will have to collect all the coins scattered among them. If you make a mistake or you want to restart the level, just press j, while to move use the commands w a s . Good luck and hope you enjoy this simple game ;)
> [Sprig App] Trinfin

- games/NavigatingDarkness.js
**Jackie Li:**
**Navigating a maze, collecting keys and stars while avoiding spikes to escape!**
**Press keys WASD to move**
> NavigatingDarkness.js

- games/Flappy-bird-v.2.js
Author: Alexandru Moga
I made a port of flappy bird for Sprig console.
Use "w" and "s" to move the bird up and down.
> [Sprig App] Flappy bird v.2

- games/cat-clicker.js
Author: BoaN235
This is a clicker game kinda like cookie clicker but much more basic
You click with the cat for catnip and you can get some from buying upgrades from the shop
> [Sprig App] cat clicker

- games/FIRE-wAr.js
Author: Elkammarr
survive and gain coins
w:  up
s: down
a: left
d: right
> [Sprig App] FIRE wAr

- games/Cat-Trap-Game.js
Author: Lorolol147
Kind of Like pac man, you need to escape from a cat by getting all the keys and going through the orange exit.
Press WASD to move and make sure to get all the ksy in the screen
> [Sprig App] Cat Trap Game

- games/Sebastian's-Game-of-Death.js
Author: UnseenBeans7
2-player pvp game inspired by Conway's Game of Life
WASD to move cursor, I to place cells
> [Sprig App] Conways's Game of Death

- scripts/plagiarism_check.py
- scripts/review.py
- src/components/big-interactive-pages/editor.tsx
- src/lib/state.ts
- src/pages/editor.astro
- src/pages/~/new.ts
Setting things up such that the review script can work with the running stack in production vs. requiring a service running locally - this helps streamline things for easy review.  Also made improvements to the review script(s) to expose errors / fail more gracefully
> Review process -> production

- games/avoid-the-bullets.js
Author: J4mik
avoid falling bombs and flying bullets
use 'w', 'a' and 'd' to move around and 's' to restart
> [Sprig App] avoid the bullets

- games/CaseOh's Castle.js
**Kris**
**Oh no! Rizzler is trapped in CaseOh's castle and the costco guys need to save him!**
**Controls: wasd for AJ, ijkl for big justice.**
**Goal: The exits (arrows) have to each be occupied by a character before the costco guys can progress. Big Justice
can push crates, and AJ can push double chunk chocolate chip cookies. The buttons must be held down with crates in order
for them to progress. Big Justice drowns, and AJ can swim. Rescue Rizzler!**
> CaseOh's Castle

- .github/workflows/build.yml
Updates upload artifact to the new version.
> Fix the build action

- games/Happy-Maze.js
Author: LifelagCheats
buggy game
Standard maze (portals at final level)
> [Sprig App] Happy Maze

- games/Echoes-of-the-Rift.js
Author: Geo-Raid
Cupcake that can time travel.
w,s,a,d for movement, j for time travel and k for pull boxes.
> [Sprig App] Echoes of the Rift

- games/step-step.js
Adds the required `description` field to the metadata about my game (step-step).
> chore(games/step-step): add description to metadata

- .github/PULL_REQUEST_TEMPLATE.md
this commit adds a checkbox to make sure people add metadata to their games
> add metadata to PR checklist

- games/Binx's-Timed-Maze.js
- games/pea-boba-maze.js
**Author: Kailey**
My game has 14 levels of different mazes that increasingly get more challenging. I took inspiration from the tutorial since it was my first time using Sprig. The goal is to get the green pea to the boba.
Press WASD to move and J to reset the current level.
> pea-boba-maze

- games/ICONIC SNAKE.js
**Author: Master Yug**
It is A modernized snake game with multiple difficulties, dynamic scoring, restart menu, and live score display. 
Use `WASD` or arrow keys (`IJKL`) to move the snake.Eat food to grow and increase your score while avoiding walls if not playing in warp mode. You can choose difficulty in the start menu and after the game is over, press `L` to return to the menu. The game also uses other keys like IJKL to choose between difficulty options and modes.
>     /*
>     @title:
>     @author:
>     @description:
>     @tags: []
>     @addedOn: 2025-MM-DD
>     */
> Added ICONIC SNAKE game

- README.md
- games/Battery_Blitz.js
What is your game about?
Maze runner with a twist (limited energy)
How do you play your game?
INSTRUCTIONS:
use WASD to move.
Batteries grant energy, stars grant energy and points.
Hazards can be moved, however they require extra energy to do so
doors move to the next level, however they take energy to unlock, using K.
If you have soft-locked yourself, or you run out of energy, J will reload the level.
Code
[x ] The game was made using the [Sprig editor](https://sprig.hackclub.com/editor).
[ x] The game is placed in the in the [/games directory](https://github.com/hackclub/sprig/tree/main/games).
[ x] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
[ x] …
> Sprig App: Battery Blitz

- games/Orb_Dungeon.js
I made the game Orb Dungeon last year but I fixed some bugs and added lore so I am updating it here also
> [Game Update] Orb Dungeon

- games/lader-climber-1.js
Author: judedanger2012
basically the whole objective is to make your way up the ladders without runing into any geese to get to the highly coveted golden hammer on every level and of corse have tons of fun as you do it.
a and d move you side to side in there repected directions w pulls you up and you wot stop unless you click l wich moves you to the next level and if you hit a bird click s to reset yourself at level 1.
> [Sprig App] lader climber 1

- games/Pickle Run.js
- games/Pickle-Run.js
**Author: Cameron Phillips**
**Ever Want To Become A Pickle Well Here Is Your Chance With Pickle Run. Play As A Pickle Exploring It's Thoughts Through Fun And Interesting Puzzels**
**Controls 
[W] To Move Upward
[S] To Move Downward
[A] To Move Left
[D] To Move Right
[J] To Start / Restart
Try To Get The Pickle To The Finish Flag by moving boxes. 
**
- [x ] The code is significantly different from all other games in the [Sprig gallery](https://sprig.hackclub.com/gallery) (except for games labeled "demo").
- [x ] The name …
> Pickle-Run

- games/Block-Dash.js
Author: DerpyDoggo11
Geometry Dash in Sprig! Reach the end to win.
Press W to Jump
> [Sprig App] Block Dash

- games/Platformation.js
**Author:**
temidaradev
Collecting coins and passing the levels but in annoying style, unbalanced character mechanics makes it annoying but also fun at the same time!
W = Jump
A = left
S = optional collecting
D = right
J = reset level
- [ x] The name of the file/game contains only alphanumeric characters, …
> Platformation.js
